apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mern-stack
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        env:
        - name: mongoroot
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: ro00t321
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: MONGO_INITDB_FEATURE_COMPATIBILITY_VERSION
          value: "5.0"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
