apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # 'root' kullanıcı adı (base64 encoded)
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==  # 'example' şifresi (base64 encoded)
