apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bbw0r1d/mern-backend:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: mongodb-uri

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace:
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

