apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  # MongoDB'nin yapılandırma dosyasını burada tanımlayabiliriz
  mongod.conf: |
    # MongoDB yapılandırma dosyası
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    net:
      bindIp: 0.0.0.0  # Dışarıdan bağlantılara izin verir
      port: 27017
    security:
      authorization: "enabled"  # Kullanıcı doğrulaması aktif
    replication:
      replSetName: rs0  # Replication Set (isteğe bağlı)
