apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: mern-stack
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    security:
      authorization: enabled
