name: Deploy to AWS EKS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository'yi Checkout Et
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. AWS CLI ve Kubectl Kurulum
    - name: Install AWS CLI and Kubectl
      run: |
        # AWS CLI kurulumu (varsa güncelleme)
        if ! command -v aws &> /dev/null; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        else
          echo "AWS CLI is already installed. Skipping installation."
        fi
        
        # Kubectl kurulumu
        sudo apt-get update && sudo apt-get install -y curl unzip
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # 3. AWS Kimlik Bilgilerini Ayarla
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 4. EKS Kümesi Oluştur
    - name: Create EKS Cluster
      run: |
        # EKS kümesi oluşturulması
        aws eks create-cluster \
          --name mern-cluster \
          --region us-east-1

        # Kümenin aktif olmasını bekle
        aws eks wait cluster-active --name mern-cluster --region us-east-1

    # 5. Kubernetes için Kubeconfig Ayarla
    - name: Update kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name mern-cluster

    - name: Mongodb Deployment
      run: |
        kubectl create ns mern-stack
        kubectl apply -f mongo-deployment.yml
        kubectl apply -f mongo-secret.yml
        kubectl apply -f mongo-configmap.yml

    # 6. Backend Deployment
    - name: Deploy Backend
      run: |
        kubectl apply -f manifest/backend-deployment.yml

    # 7. Frontend Deployment
    - name: Deploy Frontend
      run: |
        kubectl apply -f manifest/frontend-deployment.yml
