name: CI for frontend

on:
  push:
    branches:
      - main 
    paths:
      - 'frontend/**'  # Sadece frontend dizinindeki değişikliklerde tetiklenir 

jobs:
  CI-backend:
    name: CI for frontend
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 3. Build Docker Images
    - name: Build Backend Docker Image
      run: |
        docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/mern-frontend ./frontend

    # 4. Push Docker Images
    - name: Push Backend Image
      run: |
        docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/mern-frontend
